const data = {
    products: [
        {
            _id: '1',
            name: 'Crochet Shawl',
            category: 'Shawls',
            image: '/images/product1.jpg',
            price: 120,
            brand: 'Express',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Blue Jeans',
            category: 'Jeans',
            image: '/images/product2.jpg',
            price: 75,
            brand: 'JcPenny',
            rating: 4,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Button Up Shirt',
            category: 'Shirts',
            image: '/images/product3.jpg',
            price: 60,
            brand: 'Dillards',
            rating: 3.5,
            numReviews: 19,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Puffy Jacket',
            category: 'Jackets',
            image: '/images/product4.jpg',
            price: 135,
            brand: 'Nike',
            rating: 4,
            numReviews: 9,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Grey Jeans',
            category: 'Jeans',
            image: '/images/product5.jpg',
            price: 90,
            brand: 'American Eagle',
            rating: 4.8,
            numReviews: 4,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Jeans Shirt',
            category: 'Shirts',
            image: '/images/product6.jpg',
            price: 99,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 25,
            description: 'high quality product',
        },
    ],
};

export default data;